### ISSUE TITLE
Unhandled Promise rejection: Template parse errors: Can't bind to 'alert' since it isn't a known property of 'nac-alert-center'.

### ISSUE THREAD

**Issue by rdanusha** [zsfarkas/ng2-alert-center#1]
I include ng2-alert-center to myng2 project. Unfortunately this error occurred any idea ? please

**Comment by zsfarkas** [comment]
Hey. You're the first one! Thank you!

You cannot bind an alert to the alert center. Instead you can send an alert via the alert service, which you can inject into your components. 

I hope it helps.
