### ISSUE TITLE
ERROR in AlertCenterModule is not an NgModule. webpack: Failed to compile.

### ISSUE THREAD

**Issue by rdanusha** [zsfarkas/ng2-alert-center#2]
When run ng serve, It occur this error.
`"ERROR in AlertCenterModule is not an NgModule"   webpack: Failed to compile.`

![image](https://cloud.githubusercontent.com/assets/3851900/24098366/1c773fb0-0d90-11e7-87a1-6af00147762a.png)

My app.module.ts

`......
import {AlertCenterModule} from "ng2-alert-center/dist/alert-center.module";

@NgModule({
    declarations: [
        AppComponent,
        DashboardComponent,
        HeaddingComponent,
        NavbarComponent,
        BreadcrumbComponent,
        ControlMessagesComponent,
        CustomerListComponent,
        CustomerComponent,
    ],
    imports: [
        BrowserModule,
        FormsModule,
        HttpModule,
        routing,
        RouterModule,
        ReactiveFormsModule,
        AlertCenterModule,
        ModalModule
    ],
    providers: [ValidationService,CustomerService],
    bootstrap: [AppComponent]
})
export class AppModule {
}`

**Comment by zsfarkas** [comment]
Thank you. I will look at it today. Can you post your output of `ng version`.

**Comment by rdanusha** [comment]
Here are the output of ng version,

@angular/cli: 1.0.0-rc.2
node: 7.7.3
os: win32 x64
@angular/common: 2.4.10
@angular/compiler: 2.4.10
@angular/core: 2.4.10
@angular/forms: 2.4.10
@angular/http: 2.4.10
@angular/platform-browser: 2.4.10
@angular/platform-browser-dynamic: 2.4.10
@angular/router: 3.4.10
@angular/cli: 1.0.0-rc.2
@angular/compiler-cli: 2.4.10

**Comment by zsfarkas** [comment]
I can confirm this bug. However I am not sure, what the problem is. I will try to generate map files into the generated npm module. Maybe that is the problem.

**Comment by zsfarkas** [comment]
v0.2.13 should solve the problem
